# Generated by Django 4.2.16 on 2026-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("priority", models.CharField(blank=True, max_length=20, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("draft_response", models.TextField(blank=True, null=True)),
                ("is_lead", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Review", "Pending Review"),
                            ("Sent", "Sent"),
                            ("Ignored", "Ignored"),
                        ],
                        default="Pending Review",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
