# Generated by Django 4.2.16 on 2026-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_callrecord_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("message_type", models.CharField(max_length=50)),
                ("sender_handle", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("priority", models.CharField(blank=True, max_length=20, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("draft_response", models.TextField(blank=True, null=True)),
                ("is_lead", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Review", "Pending Review"),
                            ("Replied", "Replied"),
                            ("Escalated", "Escalated"),
                            ("Ignored", "Ignored"),
                        ],
                        default="Pending Review",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
