# Generated by Django 4.2.16 on 2026-06-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_socialmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lead_score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("action_items", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_sessions",
                        to="support.lead",
                    ),
                ),
            ],
        ),
    ]
