# Generated by Django 4.2.16 on 2026-06-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_lead_lead_score_voicesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("requirement", models.TextField(blank=True, null=True)),
                ("lead_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="voicesession",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_sessions",
                to="support.voicelead",
            ),
        ),
    ]
