# Generated by Django 4.2.16 on 2026-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_voicelead_alter_voicesession_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicesession",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
